### PR TITLE
Update to angular 13

### PR DESCRIPTION
**Pull request by vpetrusevici**
Hi. I tried to update your repo to Angular 13, but I can't run postinstall (ngcc) because of problem with @myndpm/dyn-forms dependency. Can you help to fix it?

```
> @matheo/angular@13.0.0.beta.0 postinstall
> ngcc --properties es2015 browser module main s --create-ivy-entry-points && node ./decorate-angular-cli.js
Compiling @myndpm/dyn-forms : main as umd
Compiling @myndpm/dyn-forms/ui-material : main as umd
Compiling @myndpm/dyn-forms/ui-native : main as umd
Error: Error on worker #1: Error: Compiled class declaration is not inside an IIFE: DynFormTreeNode in C:/Users/vladi/source/repos/angular/node_modules/@myndpm/dyn-forms/core/src/form-tree-node.service.d.ts
    at UmdRenderingFormatter.addDefinitions (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:12659:13)
    at file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13310:27
    at Array.forEach (<anonymous>)
    at Renderer.renderFile (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13307:36)
    at file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13292:36
    at Array.forEach (<anonymous>)
    at Renderer.renderProgram (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13288:46)
    at Transformer.transform (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13573:32)
    at file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13656:34
    at Worker.<anonymous> (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:13807:24)
    at ClusterMaster.onWorkerMessage (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:5126:15)
    at file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:5037:72
    at EventEmitter.<anonymous> (file:///C:/Users/vladi/source/repos/angular/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:5194:15)
    at EventEmitter.emit (node:events:390:28)
    at Worker.<anonymous> (node:internal/cluster/primary:186:13)
    at Worker.emit (node:events:390:28)
    at ChildProcess.<anonymous> (node:internal/cluster/worker:33:12)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```
Issue: https://github.com/matheo/angular/issues/45

### CODE REVIEW

**Comment by matheo** [comment]
Hey @vpetrusevici 
I've just released `@matheo/datepicker@12.10.0-beta.0`
it should be compatible with Angular v13, I will enable partial Ivy compilation tho

**Comment by byme8** [comment]
Hi, `` matheo/datepicker@12.10.0-beta.0 `` doesn't work with Angular 13

**Comment by matheo** [comment]
@byme8 thank you for the feedback!
I've published `@matheo/datepicker@12.10.0-beta.1` with Ivy partial compilation enabled to see if it works

**Comment by matheo** [comment]
YAY, I've synced the codebase with v13 and released `@matheo/datepicker@13.0.0-beta.0`
I see it running in the local website and I enabled Ivy with partial compilation, I hope it works.
Looking forward for feedback ;)

**Pull request closed without merging**
